# Based on http://conda.pydata.org/docs/travis.html
language: minimal
sudo: false
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - env: CONDA_ENV=py35
  - env: CONDA_ENV=py36
  - env: CONDA_ENV=py36-xarray-dev
  - env: CONDA_ENV=py37
  - env: CONDA_ENV=docs
  - env: CONDA_ENV=lint
  allow_failures:
  - env: CONDA_ENV=py36-xarray-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      conda env create -n test_env --file doc/environment.yml;
    elif [[ "$CONDA_ENV" == "lint" ]]; then
      conda env create -n test_env --file ci/requirements-py37.yml;
    else
      conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
    fi;
  - source activate test_env
  - conda list
  - pip install --no-deps -e .

script:
  - which python
  - python --version
  - python -OO -c "import aospy"
  - if [[ "$CONDA_ENV" == "docs" ]]; then
      conda install -c conda-forge sphinx sphinx_rtd_theme numpydoc;
      sphinx-build -n -b html -d doc/_build/doctrees doc doc/_build/html;
    elif [[ "$CONDA_ENV" == "lint" ]]; then
      flake8 -j auto aospy;
    else
      py.test aospy --cov=aospy --cov-report term-missing --verbose $EXTRA_FLAGS;
    fi

after_success:
  - coveralls
